### ISSUE TITLE
Getting an error in loop while running example code

### ISSUE THREAD

**Issue by HammadHassan924** [cdqa-suite/cdQA#285] opened 2019-10-22 08:31 UTC
Hi,

I am getting this error in loop while running the code that is provided here :
https://gist.githubusercontent.com/andrelmfarias/8d16184cb862c3f408a563c4efbfd489/raw/c478b1c61ccf52f1fff26e804aa22f09726033bd/tutorial-cdqa.py

![image](https://user-images.githubusercontent.com/20611131/67269470-3de05e00-f4d0-11e9-85c9-1f9c673c67f6.png)

**Comment by andrelmfarias** [comment] 2019-10-22 08:36
Hi,

I think your issue is a duplicate of #264 and #278 which are already solved. Could you please check the solutions there?

**Closed** 2019-11-08 13:54 UTC
