### ISSUE TITLE
multilingual data support

### ISSUE THREAD

**Issue by munggok** [cdqa-suite/cdQA#273] opened 2019-10-01 18:19 UTC
does cdQa can handle multilingual data(non-english paragraph) ?

because As far i can see, cdqa use `bert-base-cased` as bert base model

pardon my english

**Comment by andrelmfarias** [comment] 2019-10-02 11:23
Hi @munggok ,

This issue is a duplicate of: #236 

Please refer to the discussion in that issue

**Closed by andrelmfarias** 2019-10-02 11:23 UTC
